blueprint:
  name: Automatic Lock Door Based on Contact Sensor
  description: Lock the door after a certain period of time
  domain: automation
  input:
    lock:
      name: Lock
      description: This is the door lock that's being automitcally locked
      selector:
        entity:
          domain: lock
          
    contact_sensor:
      name: Contact Sensor
      description: This is the contact sensor of the door
      selector:
        entity:
          domain: binary_sensor
          device_class: contact

mode: single

trigger:
  - platform: state
    entity_id:
      - !input contact_sensor
    from: "on"
    to: "off"
  - platform: state
    entity_id:
      - !input lock
    from: locked
    to: unlocked

action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - if:
      - condition: state
        entity_id:
          - !input contact_sensor
        state: "off"
      - condition: state
        entity_id:
          - !input lock
        state: unlocked
    then:
      - service: lock.lock
        target:
          entity_id: !input lock
